### ISSUE TITLE
MirrorMod hangs when receiving defective ZIP-Stream

### ISSUE THREAD

**Issue by oli-h** [swisspush/vertx-rest-mirror#12]
MIrrorMod's ZipFileEntryIterator hides an IOException behind a RuntimeException:
https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ZipFileEntryIterator.java#L74-L76

In case of defective ZIP-Streams this leads to uncatched Exceptions in a Handler and then to a not-ended HttpServerResponse:
- https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java#L143
- https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java#L153
- https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java#L154
- https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java#L182
- https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java#L234

Additionally a further bunch of findings after code review:
- MirrorRequest is answered "200 OK" even if one or more PUTs of ZIP-Entries fail. Although the JSON-Response of the MirrorRequest then lists those resources with `success: false`, this behaviour is surprising as the caller might assume that the whole *GET the zip, extract all entries and PUT all of them" was successful
- The whole ZIP is kept in-memory multiple times:
  - as a Vertx Buffer https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java#L132
  - as a byte[] https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java#L136
  - each entry's unZIPped content as a byte[] https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java#L153-L154
  - each entry's unZIPped content as a Buffer https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java#L255
- Situation can occur where MirrorMod want to send http-response multiple times: https://github.com/swisspush/vertx-rest-mirror/blob/72e967b70c3261922d826139e30c2026b3cf770a/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java#L224-L237
- Class https://github.com/swisspush/vertx-rest-mirror/blob/develop/src/main/java/org/swisspush/mirror/ResourcesMirrorHandler.java seems to be overloaded. This makes it hard to maintain the code:
  - Delta-Value-Handling (get current value, gennerate ZIP-GET request parameter, update last value)
  - GET the ZIP
  - iterate over ZIP entries
  - PUT each entry
  - handle errors
  - create http-response

**Comment by mcweba** [comment]
fixed in release [v2.1.15](https://github.com/swisspush/vertx-rest-mirror/releases/tag/v2.1.15)
